blank_issues_enabled: false
contact_links:
  - name: Report on the new repo.
    url: https://github.com/AdvancedXRay/XRay-Mod/issues
    about: This repo is no longer used, please report issues on the multi-project repo.