name: Java CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: nanite/workflows/.github/workflows/standard-modmuss.yml@v1.2
    with:
      java-version: 17
    secrets:
      release-files: ./build/libs/*
      saps-token: ${{ secrets.SAPS_TOKEN }}
      curse-token: ${{ secrets.CURSE_DEPLOY_TOKEN }}
