name: Java CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build with Gradle
        env:
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build publish --stacktrace --no-daemon

      - name: Release to CurseForge
        env:
          CURSE_DEPLOY_TOKEN: ${{ secrets.CURSE_DEPLOY_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew curseforge --stacktrace --no-daemon

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/libs/*.jar